spring.application.name=auth-service
server.port=8081

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Oracle DB
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=system
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

jwt.secret=MySuperSecretKeyForShutterERPProject2026MySuperSecretKey

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT (IMPORTANT: MUST MATCH GATEWAY)
jwt.secret=MySuperSecretKeyForShutterERPProject2026MySuperSecretKey
jwt.expiration=86400000